# Generated by Django 3.2.3 on 2021-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=30)),
                ('stuemail', models.EmailField(max_length=30)),
                ('stupass', models.CharField(max_length=30)),
            ],
        ),
    ]
